spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      httpclient:
        connect-timeout: 45000
        response-timeout: 60000
        pool:
          max-connections: 100
          max-idle-time: 30s
          max-life-time: 60s
        compression: true
        keep-alive: true  # HTTP Keep-Alive
        tcp-no-delay: true  # Wyłącz Nagle's algorithm
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: 
              - "https://www.langlearn.top"
              - "http://localhost:3000"
              - "http://localhost:8080"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
              - PATCH
            allowedHeaders: "*"
            allowCredentials: true
            maxAge: 3600
      routes:
        # Route do Twojego backendu
        - id: language-learning-backend
          uri: ${BACKEND_URL:https://language-learning-backend-production-3ce3.up.railway.app}
          predicates:
            - Path=/api/**
          filters:
            - name: CircuitBreaker
              args:
                name: backend-circuit
                fallbackUri: forward:/fallback
                failureRateThreshold: 50  # 50% błędów = otwórz circuit
                waitDurationInOpenState: 30s  # Czekaj 30s przed testem
                slidingWindowSize: 10  # Ostatnie 10 żądań
                minimumNumberOfCalls: 5  # Minimum 5 żądań przed decyzją

        # Cached paginated words endpoint
        - id: paginated-cached
          uri: ${BACKEND_URL:https://language-learning-backend-production-3ce3.up.railway.app}
          predicates:
            - Path=/api/words/paginated
            - Method=GET
          filters:
            - AddResponseHeader=X-Cache-Status, HIT

        # Health check endpoint
        - id: health-check
          uri: ${BACKEND_URL:https://language-learning-backend-production-3ce3.up.railway.app}
          predicates:
            - Path=/actuator/health
          filters:
            - StripPrefix=0

server:
  port: ${PORT:8080}
  netty:
    connection-timeout: 30000
    h2c-max-content-length: 1048576  # 1MB
    initial-buffer-size: 128
    max-chunk-size: 8192
    max-initial-line-length: 4096
    validate-headers: false

# Logging
logging:
  level:
    org.springframework.cloud.gateway: INFO
    reactor.netty.http.client: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

# Actuator endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway,circuitbreakers
  endpoint:
    health:
      show-details: always

# Resilience4j Circuit Breaker configuration
resilience4j:
  circuitbreaker:
    instances:
      backend-circuit:
        failure-rate-threshold: 50
        wait-duration-in-open-state: 30s
        sliding-window-size: 10
        minimum-number-of-calls: 5
        permitted-number-of-calls-in-half-open-state: 3
        automatic-transition-from-open-to-half-open-enabled: true
